jobs:
  approve:
    if: github.repository_owner == 'googleapis' && github.head_ref == 'autosynth-readme'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.YOSHI_APPROVER_TOKEN}}
        script: "// only approve PRs from yoshi-automation\nif (context.payload.pull_request.user.login\
          \ !== \"yoshi-automation\") {\n  return;\n}\n\n// only approve PRs like\
          \ \"chore: release <release version>\"\nif (!context.payload.pull_request.title\
          \ === \"chore: regenerate README\") {\n  return;\n}\n\n// only approve PRs\
          \ with README.md and synth.metadata changes\nconst files = new Set(\n  (\n\
          \    await github.paginate(\n      github.pulls.listFiles.endpoint({\n \
          \       owner: context.repo.owner,\n        repo: context.repo.repo,\n \
          \       pull_number: context.payload.pull_request.number,\n      })\n  \
          \  )\n  ).map(file => file.filename)\n);\nif (files.size != 2 || !files.has(\"\
          README.md\") || !files.has(\".github/readme/synth.metadata/synth.metadata\"\
          )) {\n  return;\n}\n\n// approve README regeneration PR\nawait github.pulls.createReview({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  body: 'Rubber\
          \ stamped PR!',\n  pull_number: context.payload.pull_request.number,\n \
          \ event: 'APPROVE'\n});\n\n// attach automerge label\nawait github.issues.addLabels({\n\
          \  owner: context.repo.owner,\n  repo: context.repo.repo,\n  issue_number:\
          \ context.payload.pull_request.number,\n  labels: ['automerge']\n});\n"
name: auto-merge-readme
on:
  repository_dispatch:
    types: trigger-ga___approve-readme.yaml
