jobs:
  clirr:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      env:
        JOB_TYPE: clirr
      run: .kokoro/build.sh
  dependencies:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      run: .kokoro/dependencies.sh
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
  lint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      env:
        JOB_TYPE: lint
      run: .kokoro/build.sh
  units:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - continue-on-error: true
      run: java -version
    - continue-on-error: true
      env:
        JOB_TYPE: test
      run: .kokoro/build.sh
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
  units-java21:
    name: units (21)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Set jvm system property environment variable for surefire plugin (unit
        tests)
      run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
      shell: bash
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      env:
        JOB_TYPE: test
      run: .kokoro/build.sh
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
