jobs:
  checkstyle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Run checkstyle
      run: mvn -P lint --quiet --batch-mode checkstyle:check
      working-directory: samples/snippets
name: samples
on:
  repository_dispatch:
    types: trigger-ga___samples.yaml
